// ─────────────────────────────────────────────────────────────────────────────
// IMPORTANT — this file must be generated by the FlutterFire CLI.
//
// Steps:
//  1. Go to https://console.firebase.google.com and create a project (e.g. "AfriGlow")
//  2. Enable Authentication → Email/Password  and  Google  sign-in providers
//  3. Create a Firestore database (start in test mode, then secure with rules)
//  4. In your terminal, run:
//       dart pub global activate flutterfire_cli
//       flutterfire configure --project=<your-firebase-project-id>
//  5. Replace this entire file with the generated firebase_options.dart
//
// The placeholder below keeps the app compilable until you run the CLI.
// ─────────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run: flutterfire configure --project=<your-project-id>',
        );
    }
  }

  // ── Replace each value below with your real Firebase project values ────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeweldJ7yTcT4bnEClMhYryvwoDNSAs9w',
    appId: '1:978963949555:android:c3c2f62b23dbc170d5d486',
    messagingSenderId: '978963949555',
    projectId: 'afriglow-skinwise',
    storageBucket: 'afriglow-skinwise.firebasestorage.app',
    androidClientId: '978963949555-sqhavrf7s1fju6kt4eov830te702pqrd.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:000000000000:ios:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.flutterApplicationSkinWise',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:000000000000:web:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    authDomain: 'your-project-id.firebaseapp.com',
  );
}